### ISSUE TITLE
GETTING ERROR WHILE DOING BACKUP

### ISSUE THREAD

**Issue by sdarshil** [displague/velero-plugin-linode#1]
getting this error 

time="2022-04-01T08:36:44Z" level=error msg="Error listing backups in backup store" backupLocation=default controller=backup-sync error="rpc error: code = Unknown desc = RequestError: send request failed\ncaused by: Get https://snapshot-volume-backup.snapshot-volume-backup.us-southeast-1.linodeobjects.com/?delimiter=%2F&list-type=2&prefix=backups%2F: x509: certificate is valid for *.us-southeast-1.linodeobjects.com, *.website-us-southeast-1.linodeobjects.com, us-southeast-1.linodeobjects.com, website-us-southeast-1.linodeobjects.com, not snapshot-volume-backup.snapshot-volume-backup.us-southeast-1.linodeobjects.com" error.file="/go/src/github.com/vmware-tanzu/velero-plugin-for-aws/velero-plugin-for-aws/object_store.go:308" error.function="main.(*ObjectStore).ListCommonPrefixes" logSource="pkg/controller/backup_sync_controller.go:182"

**Comment by sdarshil** [comment]
i found this error was on my side so i solved that error but now i am getting another error which is 
  Warning  FailedAttachVolume  62s (x9 over 3m15s)    attachdetach-controller  AttachVolume.Attach failed for volume "pvc-29c090aeea174590" : rpc error: code = NotFound desc = Volume with id 101963647 not found
  
  how to resolve this ?

**Comment by displague** [comment]
@sdarshil I haven't looked at this project in a couple of years. I'm not running it today since I tore down the clusters where I was using this and haven't added Valero back in.

Guessing from the error message, you may want to ensure that the API token you created using includes Volume reading scopes.

Adding `LINODE_DEBUG: 1` to the environment of the deployment should reveal API level details (which may contain your private API token so be careful about reposting without reviewing).

**Comment by sdarshil** [comment]
hi @displague actually my api token do have the volume scope , but anyway thanks for help ! 
it would be great if you can guide in something :)

**Comment by displague** [comment]
Take a look at the container logs after enabling the debug environment variable. If the API request is being rejected (or sending the wrong ID) that would be telling. 

Likewise, `kubectl describe` the CSI and Velero resources for their state. Any added detail you could provide would be helpful.

**Comment by displague** [comment]
Looks like you found another approach:
- https://www.linode.com/community/questions/22647/how-to-take-pvc-backup-in-linode#answer-80082
- https://www.linode.com/community/questions/22181/backup-k8s-with-velero#answer-78728
